spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: 10.0.0.33:19094,10.0.0.33:29094,10.0.0.33:39094
server:
  port: 9000